### ISSUE TITLE
Make logging level configurable

### ISSUE THREAD

**Issue by only-entertainment** [ramonsaraiva/timy#9] opened 2017-04-20 22:10 UTC
To prevent the logging from getting too noisy it would be nice to set it to something other than INFO.
Great library!

**Comment by ramonsaraiva** [comment] 2017-04-21 11:33
Thanks for addressing this.
I will work on this issue when i have time, unless you want to do it.

**Comment by ramonsaraiva** [comment] 2017-09-20 21:52
Sorry for the long delay, PR that addresses the issue is merged.

**Closed as completed by ramonsaraiva** 2017-09-20 21:52 UTC
